packages:
  - apps/*
  - packages/*

catalog:
  '@live-state/sync': ^0.0.4-beta.9
  zod: 4.1.9
  '@types/react': ^19.2.0
  '@types/react-dom': ^19.2.0
  react: ^19.2.0
  react-dom: ^19.2.0

ignoredBuiltDependencies:
  - libpq
  - sharp
  - workerd

onlyBuiltDependencies:
  - '@parcel/watcher'
  - core-js
  - core-js-pure
  - esbuild
