packages:
  - apps/*
  - packages/*

catalog:
  '@live-state/sync': ^0.0.4-beta.6
  zod: 4.1.9

ignoredBuiltDependencies:
  - libpq
  - sharp
  - workerd

onlyBuiltDependencies:
  - '@parcel/watcher'
  - core-js-pure
  - esbuild
