packages:
  - apps/*
  - packages/*
onlyBuiltDependencies:
  - '@biomejs/biome'
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - core-js
  - core-js-pure
  - esbuild
  - libpq
  - rolldown
  - unrs-resolver
