export const RED_GLARE_UNIFORMS = {
  u_aberration: { value: 0.2 },
  u_background: { value: [5 / 255, 0, 0] as number[] },
  u_bloom: { value: 1.44 },
  u_cellSize: { value: 0.175 },
  u_color: { value: [1, 20 / 255, 48 / 255] as number[] },
  u_contrast: { value: 1 },
  u_density: { value: 0.69 },
  u_exposure: { value: -0.12 },
  u_glow: { value: 1.11 },
  u_haze: { value: 0.155 },
  u_highlight: { value: [1, 1, 1] as number[] },
  u_intensity: { value: 0.4 },
  u_layers: { value: 6 },
  u_life: { value: 0.85 },
  u_noise: { value: 0.8 },
  u_saturation: { value: 1 },
  u_seed: { value: 12 },
  u_sizeMax: { value: 0.22 },
  u_sizeMin: { value: 0.03 },
  u_softness: { value: 2.24 },
  u_speed: { value: 0.245 },
  u_spread: { value: 1.2 },
} as const;
