/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as NowAllowedRouteImport } from './routes/now-allowed'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as PublicRouteRouteImport } from './routes/_public/route'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as AppWorkspaceRouteRouteImport } from './routes/app/_workspace/route'
import { Route as SupportSlugIndexRouteImport } from './routes/support/$slug/index'
import { Route as AppOnboardingIndexRouteImport } from './routes/app/onboarding/index'
import { Route as PublicUpdatesIndexRouteImport } from './routes/_public/updates/index'
import { Route as SupportSlugSitemapDotxmlRouteImport } from './routes/support/$slug/sitemap[.]xml'
import { Route as SupportSlugRobotsDottxtRouteImport } from './routes/support/$slug/robots[.]txt'
import { Route as AppOnboardingNewRouteImport } from './routes/app/onboarding/new'
import { Route as AppInvitationIdRouteImport } from './routes/app/invitation.$id'
import { Route as PublicLegalTermsOfServiceRouteImport } from './routes/_public/legal/terms-of-service'
import { Route as PublicLegalPrivacyPolicyRouteImport } from './routes/_public/legal/privacy-policy'
import { Route as AppWorkspaceSettingsRouteRouteImport } from './routes/app/_workspace/settings/route'
import { Route as AppWorkspaceMainRouteRouteImport } from './routes/app/_workspace/_main/route'
import { Route as SupportSlugThreadsIndexRouteImport } from './routes/support/$slug/threads/index'
import { Route as AppWorkspaceSettingsIndexRouteImport } from './routes/app/_workspace/settings/index'
import { Route as AppWorkspaceMainIndexRouteImport } from './routes/app/_workspace/_main/index'
import { Route as SupportSlugThreadsIdRouteImport } from './routes/support/$slug/threads/$id'
import { Route as AppWorkspaceSettingsUserIndexRouteImport } from './routes/app/_workspace/settings/user/index'
import { Route as AppWorkspaceSettingsOrganizationIndexRouteImport } from './routes/app/_workspace/settings/organization/index'
import { Route as AppWorkspaceMainThreadsIndexRouteImport } from './routes/app/_workspace/_main/threads/index'
import { Route as AppWorkspaceSettingsOrganizationTeamRouteImport } from './routes/app/_workspace/settings/organization/team'
import { Route as AppWorkspaceSettingsOrganizationBillingRouteImport } from './routes/app/_workspace/settings/organization/billing'
import { Route as AppWorkspaceMainThreadsIdRouteImport } from './routes/app/_workspace/_main/threads/$id'
import { Route as AppWorkspaceSettingsOrganizationIntegrationIndexRouteImport } from './routes/app/_workspace/settings/organization/integration/index'
import { Route as AppWorkspaceMainThreadsArchiveIndexRouteImport } from './routes/app/_workspace/_main/threads/archive/index'
import { Route as AppWorkspaceMainThreadsArchiveIdRouteImport } from './routes/app/_workspace/_main/threads/archive/$id'
import { Route as AppWorkspaceSettingsOrganizationIntegrationDiscordIndexRouteImport } from './routes/app/_workspace/settings/organization/integration/discord/index'
import { Route as AppWorkspaceSettingsOrganizationIntegrationDiscordRedirectRouteImport } from './routes/app/_workspace/settings/organization/integration/discord/redirect'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const NowAllowedRoute = NowAllowedRouteImport.update({
  id: '/now-allowed',
  path: '/now-allowed',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWorkspaceRouteRoute = AppWorkspaceRouteRouteImport.update({
  id: '/_workspace',
  getParentRoute: () => AppRouteRoute,
} as any)
const SupportSlugIndexRoute = SupportSlugIndexRouteImport.update({
  id: '/support/$slug/',
  path: '/support/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppOnboardingIndexRoute = AppOnboardingIndexRouteImport.update({
  id: '/onboarding/',
  path: '/onboarding/',
  getParentRoute: () => AppRouteRoute,
} as any)
const PublicUpdatesIndexRoute = PublicUpdatesIndexRouteImport.update({
  id: '/updates/',
  path: '/updates/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const SupportSlugSitemapDotxmlRoute =
  SupportSlugSitemapDotxmlRouteImport.update({
    id: '/support/$slug/sitemap.xml',
    path: '/support/$slug/sitemap.xml',
    getParentRoute: () => rootRouteImport,
  } as any)
const SupportSlugRobotsDottxtRoute = SupportSlugRobotsDottxtRouteImport.update({
  id: '/support/$slug/robots.txt',
  path: '/support/$slug/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const AppOnboardingNewRoute = AppOnboardingNewRouteImport.update({
  id: '/onboarding/new',
  path: '/onboarding/new',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppInvitationIdRoute = AppInvitationIdRouteImport.update({
  id: '/invitation/$id',
  path: '/invitation/$id',
  getParentRoute: () => AppRouteRoute,
} as any)
const PublicLegalTermsOfServiceRoute =
  PublicLegalTermsOfServiceRouteImport.update({
    id: '/legal/terms-of-service',
    path: '/legal/terms-of-service',
    getParentRoute: () => PublicRouteRoute,
  } as any)
const PublicLegalPrivacyPolicyRoute =
  PublicLegalPrivacyPolicyRouteImport.update({
    id: '/legal/privacy-policy',
    path: '/legal/privacy-policy',
    getParentRoute: () => PublicRouteRoute,
  } as any)
const AppWorkspaceSettingsRouteRoute =
  AppWorkspaceSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AppWorkspaceRouteRoute,
  } as any)
const AppWorkspaceMainRouteRoute = AppWorkspaceMainRouteRouteImport.update({
  id: '/_main',
  getParentRoute: () => AppWorkspaceRouteRoute,
} as any)
const SupportSlugThreadsIndexRoute = SupportSlugThreadsIndexRouteImport.update({
  id: '/support/$slug/threads/',
  path: '/support/$slug/threads/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWorkspaceSettingsIndexRoute =
  AppWorkspaceSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppWorkspaceSettingsRouteRoute,
  } as any)
const AppWorkspaceMainIndexRoute = AppWorkspaceMainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppWorkspaceMainRouteRoute,
} as any)
const SupportSlugThreadsIdRoute = SupportSlugThreadsIdRouteImport.update({
  id: '/support/$slug/threads/$id',
  path: '/support/$slug/threads/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWorkspaceSettingsUserIndexRoute =
  AppWorkspaceSettingsUserIndexRouteImport.update({
    id: '/user/',
    path: '/user/',
    getParentRoute: () => AppWorkspaceSettingsRouteRoute,
  } as any)
const AppWorkspaceSettingsOrganizationIndexRoute =
  AppWorkspaceSettingsOrganizationIndexRouteImport.update({
    id: '/organization/',
    path: '/organization/',
    getParentRoute: () => AppWorkspaceSettingsRouteRoute,
  } as any)
const AppWorkspaceMainThreadsIndexRoute =
  AppWorkspaceMainThreadsIndexRouteImport.update({
    id: '/threads/',
    path: '/threads/',
    getParentRoute: () => AppWorkspaceMainRouteRoute,
  } as any)
const AppWorkspaceSettingsOrganizationTeamRoute =
  AppWorkspaceSettingsOrganizationTeamRouteImport.update({
    id: '/organization/team',
    path: '/organization/team',
    getParentRoute: () => AppWorkspaceSettingsRouteRoute,
  } as any)
const AppWorkspaceSettingsOrganizationBillingRoute =
  AppWorkspaceSettingsOrganizationBillingRouteImport.update({
    id: '/organization/billing',
    path: '/organization/billing',
    getParentRoute: () => AppWorkspaceSettingsRouteRoute,
  } as any)
const AppWorkspaceMainThreadsIdRoute =
  AppWorkspaceMainThreadsIdRouteImport.update({
    id: '/threads/$id',
    path: '/threads/$id',
    getParentRoute: () => AppWorkspaceMainRouteRoute,
  } as any)
const AppWorkspaceSettingsOrganizationIntegrationIndexRoute =
  AppWorkspaceSettingsOrganizationIntegrationIndexRouteImport.update({
    id: '/organization/integration/',
    path: '/organization/integration/',
    getParentRoute: () => AppWorkspaceSettingsRouteRoute,
  } as any)
const AppWorkspaceMainThreadsArchiveIndexRoute =
  AppWorkspaceMainThreadsArchiveIndexRouteImport.update({
    id: '/threads/archive/',
    path: '/threads/archive/',
    getParentRoute: () => AppWorkspaceMainRouteRoute,
  } as any)
const AppWorkspaceMainThreadsArchiveIdRoute =
  AppWorkspaceMainThreadsArchiveIdRouteImport.update({
    id: '/threads/archive/$id',
    path: '/threads/archive/$id',
    getParentRoute: () => AppWorkspaceMainRouteRoute,
  } as any)
const AppWorkspaceSettingsOrganizationIntegrationDiscordIndexRoute =
  AppWorkspaceSettingsOrganizationIntegrationDiscordIndexRouteImport.update({
    id: '/organization/integration/discord/',
    path: '/organization/integration/discord/',
    getParentRoute: () => AppWorkspaceSettingsRouteRoute,
  } as any)
const AppWorkspaceSettingsOrganizationIntegrationDiscordRedirectRoute =
  AppWorkspaceSettingsOrganizationIntegrationDiscordRedirectRouteImport.update({
    id: '/organization/integration/discord/redirect',
    path: '/organization/integration/discord/redirect',
    getParentRoute: () => AppWorkspaceSettingsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/app': typeof AppWorkspaceMainRouteRouteWithChildren
  '/now-allowed': typeof NowAllowedRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/$': typeof ApiSplatRoute
  '/': typeof PublicIndexRoute
  '/app/settings': typeof AppWorkspaceSettingsRouteRouteWithChildren
  '/legal/privacy-policy': typeof PublicLegalPrivacyPolicyRoute
  '/legal/terms-of-service': typeof PublicLegalTermsOfServiceRoute
  '/app/invitation/$id': typeof AppInvitationIdRoute
  '/app/onboarding/new': typeof AppOnboardingNewRoute
  '/support/$slug/robots.txt': typeof SupportSlugRobotsDottxtRoute
  '/support/$slug/sitemap.xml': typeof SupportSlugSitemapDotxmlRoute
  '/updates': typeof PublicUpdatesIndexRoute
  '/app/onboarding': typeof AppOnboardingIndexRoute
  '/support/$slug': typeof SupportSlugIndexRoute
  '/support/$slug/threads/$id': typeof SupportSlugThreadsIdRoute
  '/app/': typeof AppWorkspaceMainIndexRoute
  '/app/settings/': typeof AppWorkspaceSettingsIndexRoute
  '/support/$slug/threads': typeof SupportSlugThreadsIndexRoute
  '/app/threads/$id': typeof AppWorkspaceMainThreadsIdRoute
  '/app/settings/organization/billing': typeof AppWorkspaceSettingsOrganizationBillingRoute
  '/app/settings/organization/team': typeof AppWorkspaceSettingsOrganizationTeamRoute
  '/app/threads': typeof AppWorkspaceMainThreadsIndexRoute
  '/app/settings/organization': typeof AppWorkspaceSettingsOrganizationIndexRoute
  '/app/settings/user': typeof AppWorkspaceSettingsUserIndexRoute
  '/app/threads/archive/$id': typeof AppWorkspaceMainThreadsArchiveIdRoute
  '/app/threads/archive': typeof AppWorkspaceMainThreadsArchiveIndexRoute
  '/app/settings/organization/integration': typeof AppWorkspaceSettingsOrganizationIntegrationIndexRoute
  '/app/settings/organization/integration/discord/redirect': typeof AppWorkspaceSettingsOrganizationIntegrationDiscordRedirectRoute
  '/app/settings/organization/integration/discord': typeof AppWorkspaceSettingsOrganizationIntegrationDiscordIndexRoute
}
export interface FileRoutesByTo {
  '/app': typeof AppWorkspaceMainIndexRoute
  '/now-allowed': typeof NowAllowedRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/$': typeof ApiSplatRoute
  '/': typeof PublicIndexRoute
  '/legal/privacy-policy': typeof PublicLegalPrivacyPolicyRoute
  '/legal/terms-of-service': typeof PublicLegalTermsOfServiceRoute
  '/app/invitation/$id': typeof AppInvitationIdRoute
  '/app/onboarding/new': typeof AppOnboardingNewRoute
  '/support/$slug/robots.txt': typeof SupportSlugRobotsDottxtRoute
  '/support/$slug/sitemap.xml': typeof SupportSlugSitemapDotxmlRoute
  '/updates': typeof PublicUpdatesIndexRoute
  '/app/onboarding': typeof AppOnboardingIndexRoute
  '/support/$slug': typeof SupportSlugIndexRoute
  '/support/$slug/threads/$id': typeof SupportSlugThreadsIdRoute
  '/app/settings': typeof AppWorkspaceSettingsIndexRoute
  '/support/$slug/threads': typeof SupportSlugThreadsIndexRoute
  '/app/threads/$id': typeof AppWorkspaceMainThreadsIdRoute
  '/app/settings/organization/billing': typeof AppWorkspaceSettingsOrganizationBillingRoute
  '/app/settings/organization/team': typeof AppWorkspaceSettingsOrganizationTeamRoute
  '/app/threads': typeof AppWorkspaceMainThreadsIndexRoute
  '/app/settings/organization': typeof AppWorkspaceSettingsOrganizationIndexRoute
  '/app/settings/user': typeof AppWorkspaceSettingsUserIndexRoute
  '/app/threads/archive/$id': typeof AppWorkspaceMainThreadsArchiveIdRoute
  '/app/threads/archive': typeof AppWorkspaceMainThreadsArchiveIndexRoute
  '/app/settings/organization/integration': typeof AppWorkspaceSettingsOrganizationIntegrationIndexRoute
  '/app/settings/organization/integration/discord/redirect': typeof AppWorkspaceSettingsOrganizationIntegrationDiscordRedirectRoute
  '/app/settings/organization/integration/discord': typeof AppWorkspaceSettingsOrganizationIntegrationDiscordIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_public': typeof PublicRouteRouteWithChildren
  '/app': typeof AppRouteRouteWithChildren
  '/now-allowed': typeof NowAllowedRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/app/_workspace': typeof AppWorkspaceRouteRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/_public/': typeof PublicIndexRoute
  '/app/_workspace/_main': typeof AppWorkspaceMainRouteRouteWithChildren
  '/app/_workspace/settings': typeof AppWorkspaceSettingsRouteRouteWithChildren
  '/_public/legal/privacy-policy': typeof PublicLegalPrivacyPolicyRoute
  '/_public/legal/terms-of-service': typeof PublicLegalTermsOfServiceRoute
  '/app/invitation/$id': typeof AppInvitationIdRoute
  '/app/onboarding/new': typeof AppOnboardingNewRoute
  '/support/$slug/robots.txt': typeof SupportSlugRobotsDottxtRoute
  '/support/$slug/sitemap.xml': typeof SupportSlugSitemapDotxmlRoute
  '/_public/updates/': typeof PublicUpdatesIndexRoute
  '/app/onboarding/': typeof AppOnboardingIndexRoute
  '/support/$slug/': typeof SupportSlugIndexRoute
  '/support/$slug/threads/$id': typeof SupportSlugThreadsIdRoute
  '/app/_workspace/_main/': typeof AppWorkspaceMainIndexRoute
  '/app/_workspace/settings/': typeof AppWorkspaceSettingsIndexRoute
  '/support/$slug/threads/': typeof SupportSlugThreadsIndexRoute
  '/app/_workspace/_main/threads/$id': typeof AppWorkspaceMainThreadsIdRoute
  '/app/_workspace/settings/organization/billing': typeof AppWorkspaceSettingsOrganizationBillingRoute
  '/app/_workspace/settings/organization/team': typeof AppWorkspaceSettingsOrganizationTeamRoute
  '/app/_workspace/_main/threads/': typeof AppWorkspaceMainThreadsIndexRoute
  '/app/_workspace/settings/organization/': typeof AppWorkspaceSettingsOrganizationIndexRoute
  '/app/_workspace/settings/user/': typeof AppWorkspaceSettingsUserIndexRoute
  '/app/_workspace/_main/threads/archive/$id': typeof AppWorkspaceMainThreadsArchiveIdRoute
  '/app/_workspace/_main/threads/archive/': typeof AppWorkspaceMainThreadsArchiveIndexRoute
  '/app/_workspace/settings/organization/integration/': typeof AppWorkspaceSettingsOrganizationIntegrationIndexRoute
  '/app/_workspace/settings/organization/integration/discord/redirect': typeof AppWorkspaceSettingsOrganizationIntegrationDiscordRedirectRoute
  '/app/_workspace/settings/organization/integration/discord/': typeof AppWorkspaceSettingsOrganizationIntegrationDiscordIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/app'
    | '/now-allowed'
    | '/robots.txt'
    | '/sign-in'
    | '/sign-up'
    | '/sitemap.xml'
    | '/api/$'
    | '/'
    | '/app/settings'
    | '/legal/privacy-policy'
    | '/legal/terms-of-service'
    | '/app/invitation/$id'
    | '/app/onboarding/new'
    | '/support/$slug/robots.txt'
    | '/support/$slug/sitemap.xml'
    | '/updates'
    | '/app/onboarding'
    | '/support/$slug'
    | '/support/$slug/threads/$id'
    | '/app/'
    | '/app/settings/'
    | '/support/$slug/threads'
    | '/app/threads/$id'
    | '/app/settings/organization/billing'
    | '/app/settings/organization/team'
    | '/app/threads'
    | '/app/settings/organization'
    | '/app/settings/user'
    | '/app/threads/archive/$id'
    | '/app/threads/archive'
    | '/app/settings/organization/integration'
    | '/app/settings/organization/integration/discord/redirect'
    | '/app/settings/organization/integration/discord'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/app'
    | '/now-allowed'
    | '/robots.txt'
    | '/sign-in'
    | '/sign-up'
    | '/sitemap.xml'
    | '/api/$'
    | '/'
    | '/legal/privacy-policy'
    | '/legal/terms-of-service'
    | '/app/invitation/$id'
    | '/app/onboarding/new'
    | '/support/$slug/robots.txt'
    | '/support/$slug/sitemap.xml'
    | '/updates'
    | '/app/onboarding'
    | '/support/$slug'
    | '/support/$slug/threads/$id'
    | '/app/settings'
    | '/support/$slug/threads'
    | '/app/threads/$id'
    | '/app/settings/organization/billing'
    | '/app/settings/organization/team'
    | '/app/threads'
    | '/app/settings/organization'
    | '/app/settings/user'
    | '/app/threads/archive/$id'
    | '/app/threads/archive'
    | '/app/settings/organization/integration'
    | '/app/settings/organization/integration/discord/redirect'
    | '/app/settings/organization/integration/discord'
  id:
    | '__root__'
    | '/_public'
    | '/app'
    | '/now-allowed'
    | '/robots.txt'
    | '/sign-in'
    | '/sign-up'
    | '/sitemap.xml'
    | '/app/_workspace'
    | '/api/$'
    | '/_public/'
    | '/app/_workspace/_main'
    | '/app/_workspace/settings'
    | '/_public/legal/privacy-policy'
    | '/_public/legal/terms-of-service'
    | '/app/invitation/$id'
    | '/app/onboarding/new'
    | '/support/$slug/robots.txt'
    | '/support/$slug/sitemap.xml'
    | '/_public/updates/'
    | '/app/onboarding/'
    | '/support/$slug/'
    | '/support/$slug/threads/$id'
    | '/app/_workspace/_main/'
    | '/app/_workspace/settings/'
    | '/support/$slug/threads/'
    | '/app/_workspace/_main/threads/$id'
    | '/app/_workspace/settings/organization/billing'
    | '/app/_workspace/settings/organization/team'
    | '/app/_workspace/_main/threads/'
    | '/app/_workspace/settings/organization/'
    | '/app/_workspace/settings/user/'
    | '/app/_workspace/_main/threads/archive/$id'
    | '/app/_workspace/_main/threads/archive/'
    | '/app/_workspace/settings/organization/integration/'
    | '/app/_workspace/settings/organization/integration/discord/redirect'
    | '/app/_workspace/settings/organization/integration/discord/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
  AppRouteRoute: typeof AppRouteRouteWithChildren
  NowAllowedRoute: typeof NowAllowedRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiSplatRoute: typeof ApiSplatRoute
  SupportSlugRobotsDottxtRoute: typeof SupportSlugRobotsDottxtRoute
  SupportSlugSitemapDotxmlRoute: typeof SupportSlugSitemapDotxmlRoute
  SupportSlugIndexRoute: typeof SupportSlugIndexRoute
  SupportSlugThreadsIdRoute: typeof SupportSlugThreadsIdRoute
  SupportSlugThreadsIndexRoute: typeof SupportSlugThreadsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/now-allowed': {
      id: '/now-allowed'
      path: '/now-allowed'
      fullPath: '/now-allowed'
      preLoaderRoute: typeof NowAllowedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/_workspace': {
      id: '/app/_workspace'
      path: ''
      fullPath: '/app'
      preLoaderRoute: typeof AppWorkspaceRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/support/$slug/': {
      id: '/support/$slug/'
      path: '/support/$slug'
      fullPath: '/support/$slug'
      preLoaderRoute: typeof SupportSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/onboarding/': {
      id: '/app/onboarding/'
      path: '/onboarding'
      fullPath: '/app/onboarding'
      preLoaderRoute: typeof AppOnboardingIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_public/updates/': {
      id: '/_public/updates/'
      path: '/updates'
      fullPath: '/updates'
      preLoaderRoute: typeof PublicUpdatesIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/support/$slug/sitemap.xml': {
      id: '/support/$slug/sitemap.xml'
      path: '/support/$slug/sitemap.xml'
      fullPath: '/support/$slug/sitemap.xml'
      preLoaderRoute: typeof SupportSlugSitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support/$slug/robots.txt': {
      id: '/support/$slug/robots.txt'
      path: '/support/$slug/robots.txt'
      fullPath: '/support/$slug/robots.txt'
      preLoaderRoute: typeof SupportSlugRobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/onboarding/new': {
      id: '/app/onboarding/new'
      path: '/onboarding/new'
      fullPath: '/app/onboarding/new'
      preLoaderRoute: typeof AppOnboardingNewRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/invitation/$id': {
      id: '/app/invitation/$id'
      path: '/invitation/$id'
      fullPath: '/app/invitation/$id'
      preLoaderRoute: typeof AppInvitationIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_public/legal/terms-of-service': {
      id: '/_public/legal/terms-of-service'
      path: '/legal/terms-of-service'
      fullPath: '/legal/terms-of-service'
      preLoaderRoute: typeof PublicLegalTermsOfServiceRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/legal/privacy-policy': {
      id: '/_public/legal/privacy-policy'
      path: '/legal/privacy-policy'
      fullPath: '/legal/privacy-policy'
      preLoaderRoute: typeof PublicLegalPrivacyPolicyRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/app/_workspace/settings': {
      id: '/app/_workspace/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppWorkspaceSettingsRouteRouteImport
      parentRoute: typeof AppWorkspaceRouteRoute
    }
    '/app/_workspace/_main': {
      id: '/app/_workspace/_main'
      path: ''
      fullPath: '/app'
      preLoaderRoute: typeof AppWorkspaceMainRouteRouteImport
      parentRoute: typeof AppWorkspaceRouteRoute
    }
    '/support/$slug/threads/': {
      id: '/support/$slug/threads/'
      path: '/support/$slug/threads'
      fullPath: '/support/$slug/threads'
      preLoaderRoute: typeof SupportSlugThreadsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/_workspace/settings/': {
      id: '/app/_workspace/settings/'
      path: '/'
      fullPath: '/app/settings/'
      preLoaderRoute: typeof AppWorkspaceSettingsIndexRouteImport
      parentRoute: typeof AppWorkspaceSettingsRouteRoute
    }
    '/app/_workspace/_main/': {
      id: '/app/_workspace/_main/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppWorkspaceMainIndexRouteImport
      parentRoute: typeof AppWorkspaceMainRouteRoute
    }
    '/support/$slug/threads/$id': {
      id: '/support/$slug/threads/$id'
      path: '/support/$slug/threads/$id'
      fullPath: '/support/$slug/threads/$id'
      preLoaderRoute: typeof SupportSlugThreadsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/_workspace/settings/user/': {
      id: '/app/_workspace/settings/user/'
      path: '/user'
      fullPath: '/app/settings/user'
      preLoaderRoute: typeof AppWorkspaceSettingsUserIndexRouteImport
      parentRoute: typeof AppWorkspaceSettingsRouteRoute
    }
    '/app/_workspace/settings/organization/': {
      id: '/app/_workspace/settings/organization/'
      path: '/organization'
      fullPath: '/app/settings/organization'
      preLoaderRoute: typeof AppWorkspaceSettingsOrganizationIndexRouteImport
      parentRoute: typeof AppWorkspaceSettingsRouteRoute
    }
    '/app/_workspace/_main/threads/': {
      id: '/app/_workspace/_main/threads/'
      path: '/threads'
      fullPath: '/app/threads'
      preLoaderRoute: typeof AppWorkspaceMainThreadsIndexRouteImport
      parentRoute: typeof AppWorkspaceMainRouteRoute
    }
    '/app/_workspace/settings/organization/team': {
      id: '/app/_workspace/settings/organization/team'
      path: '/organization/team'
      fullPath: '/app/settings/organization/team'
      preLoaderRoute: typeof AppWorkspaceSettingsOrganizationTeamRouteImport
      parentRoute: typeof AppWorkspaceSettingsRouteRoute
    }
    '/app/_workspace/settings/organization/billing': {
      id: '/app/_workspace/settings/organization/billing'
      path: '/organization/billing'
      fullPath: '/app/settings/organization/billing'
      preLoaderRoute: typeof AppWorkspaceSettingsOrganizationBillingRouteImport
      parentRoute: typeof AppWorkspaceSettingsRouteRoute
    }
    '/app/_workspace/_main/threads/$id': {
      id: '/app/_workspace/_main/threads/$id'
      path: '/threads/$id'
      fullPath: '/app/threads/$id'
      preLoaderRoute: typeof AppWorkspaceMainThreadsIdRouteImport
      parentRoute: typeof AppWorkspaceMainRouteRoute
    }
    '/app/_workspace/settings/organization/integration/': {
      id: '/app/_workspace/settings/organization/integration/'
      path: '/organization/integration'
      fullPath: '/app/settings/organization/integration'
      preLoaderRoute: typeof AppWorkspaceSettingsOrganizationIntegrationIndexRouteImport
      parentRoute: typeof AppWorkspaceSettingsRouteRoute
    }
    '/app/_workspace/_main/threads/archive/': {
      id: '/app/_workspace/_main/threads/archive/'
      path: '/threads/archive'
      fullPath: '/app/threads/archive'
      preLoaderRoute: typeof AppWorkspaceMainThreadsArchiveIndexRouteImport
      parentRoute: typeof AppWorkspaceMainRouteRoute
    }
    '/app/_workspace/_main/threads/archive/$id': {
      id: '/app/_workspace/_main/threads/archive/$id'
      path: '/threads/archive/$id'
      fullPath: '/app/threads/archive/$id'
      preLoaderRoute: typeof AppWorkspaceMainThreadsArchiveIdRouteImport
      parentRoute: typeof AppWorkspaceMainRouteRoute
    }
    '/app/_workspace/settings/organization/integration/discord/': {
      id: '/app/_workspace/settings/organization/integration/discord/'
      path: '/organization/integration/discord'
      fullPath: '/app/settings/organization/integration/discord'
      preLoaderRoute: typeof AppWorkspaceSettingsOrganizationIntegrationDiscordIndexRouteImport
      parentRoute: typeof AppWorkspaceSettingsRouteRoute
    }
    '/app/_workspace/settings/organization/integration/discord/redirect': {
      id: '/app/_workspace/settings/organization/integration/discord/redirect'
      path: '/organization/integration/discord/redirect'
      fullPath: '/app/settings/organization/integration/discord/redirect'
      preLoaderRoute: typeof AppWorkspaceSettingsOrganizationIntegrationDiscordRedirectRouteImport
      parentRoute: typeof AppWorkspaceSettingsRouteRoute
    }
  }
}

interface PublicRouteRouteChildren {
  PublicIndexRoute: typeof PublicIndexRoute
  PublicLegalPrivacyPolicyRoute: typeof PublicLegalPrivacyPolicyRoute
  PublicLegalTermsOfServiceRoute: typeof PublicLegalTermsOfServiceRoute
  PublicUpdatesIndexRoute: typeof PublicUpdatesIndexRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicIndexRoute: PublicIndexRoute,
  PublicLegalPrivacyPolicyRoute: PublicLegalPrivacyPolicyRoute,
  PublicLegalTermsOfServiceRoute: PublicLegalTermsOfServiceRoute,
  PublicUpdatesIndexRoute: PublicUpdatesIndexRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

interface AppWorkspaceMainRouteRouteChildren {
  AppWorkspaceMainIndexRoute: typeof AppWorkspaceMainIndexRoute
  AppWorkspaceMainThreadsIdRoute: typeof AppWorkspaceMainThreadsIdRoute
  AppWorkspaceMainThreadsIndexRoute: typeof AppWorkspaceMainThreadsIndexRoute
  AppWorkspaceMainThreadsArchiveIdRoute: typeof AppWorkspaceMainThreadsArchiveIdRoute
  AppWorkspaceMainThreadsArchiveIndexRoute: typeof AppWorkspaceMainThreadsArchiveIndexRoute
}

const AppWorkspaceMainRouteRouteChildren: AppWorkspaceMainRouteRouteChildren = {
  AppWorkspaceMainIndexRoute: AppWorkspaceMainIndexRoute,
  AppWorkspaceMainThreadsIdRoute: AppWorkspaceMainThreadsIdRoute,
  AppWorkspaceMainThreadsIndexRoute: AppWorkspaceMainThreadsIndexRoute,
  AppWorkspaceMainThreadsArchiveIdRoute: AppWorkspaceMainThreadsArchiveIdRoute,
  AppWorkspaceMainThreadsArchiveIndexRoute:
    AppWorkspaceMainThreadsArchiveIndexRoute,
}

const AppWorkspaceMainRouteRouteWithChildren =
  AppWorkspaceMainRouteRoute._addFileChildren(
    AppWorkspaceMainRouteRouteChildren,
  )

interface AppWorkspaceSettingsRouteRouteChildren {
  AppWorkspaceSettingsIndexRoute: typeof AppWorkspaceSettingsIndexRoute
  AppWorkspaceSettingsOrganizationBillingRoute: typeof AppWorkspaceSettingsOrganizationBillingRoute
  AppWorkspaceSettingsOrganizationTeamRoute: typeof AppWorkspaceSettingsOrganizationTeamRoute
  AppWorkspaceSettingsOrganizationIndexRoute: typeof AppWorkspaceSettingsOrganizationIndexRoute
  AppWorkspaceSettingsUserIndexRoute: typeof AppWorkspaceSettingsUserIndexRoute
  AppWorkspaceSettingsOrganizationIntegrationIndexRoute: typeof AppWorkspaceSettingsOrganizationIntegrationIndexRoute
  AppWorkspaceSettingsOrganizationIntegrationDiscordRedirectRoute: typeof AppWorkspaceSettingsOrganizationIntegrationDiscordRedirectRoute
  AppWorkspaceSettingsOrganizationIntegrationDiscordIndexRoute: typeof AppWorkspaceSettingsOrganizationIntegrationDiscordIndexRoute
}

const AppWorkspaceSettingsRouteRouteChildren: AppWorkspaceSettingsRouteRouteChildren =
  {
    AppWorkspaceSettingsIndexRoute: AppWorkspaceSettingsIndexRoute,
    AppWorkspaceSettingsOrganizationBillingRoute:
      AppWorkspaceSettingsOrganizationBillingRoute,
    AppWorkspaceSettingsOrganizationTeamRoute:
      AppWorkspaceSettingsOrganizationTeamRoute,
    AppWorkspaceSettingsOrganizationIndexRoute:
      AppWorkspaceSettingsOrganizationIndexRoute,
    AppWorkspaceSettingsUserIndexRoute: AppWorkspaceSettingsUserIndexRoute,
    AppWorkspaceSettingsOrganizationIntegrationIndexRoute:
      AppWorkspaceSettingsOrganizationIntegrationIndexRoute,
    AppWorkspaceSettingsOrganizationIntegrationDiscordRedirectRoute:
      AppWorkspaceSettingsOrganizationIntegrationDiscordRedirectRoute,
    AppWorkspaceSettingsOrganizationIntegrationDiscordIndexRoute:
      AppWorkspaceSettingsOrganizationIntegrationDiscordIndexRoute,
  }

const AppWorkspaceSettingsRouteRouteWithChildren =
  AppWorkspaceSettingsRouteRoute._addFileChildren(
    AppWorkspaceSettingsRouteRouteChildren,
  )

interface AppWorkspaceRouteRouteChildren {
  AppWorkspaceMainRouteRoute: typeof AppWorkspaceMainRouteRouteWithChildren
  AppWorkspaceSettingsRouteRoute: typeof AppWorkspaceSettingsRouteRouteWithChildren
}

const AppWorkspaceRouteRouteChildren: AppWorkspaceRouteRouteChildren = {
  AppWorkspaceMainRouteRoute: AppWorkspaceMainRouteRouteWithChildren,
  AppWorkspaceSettingsRouteRoute: AppWorkspaceSettingsRouteRouteWithChildren,
}

const AppWorkspaceRouteRouteWithChildren =
  AppWorkspaceRouteRoute._addFileChildren(AppWorkspaceRouteRouteChildren)

interface AppRouteRouteChildren {
  AppWorkspaceRouteRoute: typeof AppWorkspaceRouteRouteWithChildren
  AppInvitationIdRoute: typeof AppInvitationIdRoute
  AppOnboardingNewRoute: typeof AppOnboardingNewRoute
  AppOnboardingIndexRoute: typeof AppOnboardingIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppWorkspaceRouteRoute: AppWorkspaceRouteRouteWithChildren,
  AppInvitationIdRoute: AppInvitationIdRoute,
  AppOnboardingNewRoute: AppOnboardingNewRoute,
  AppOnboardingIndexRoute: AppOnboardingIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  PublicRouteRoute: PublicRouteRouteWithChildren,
  AppRouteRoute: AppRouteRouteWithChildren,
  NowAllowedRoute: NowAllowedRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiSplatRoute: ApiSplatRoute,
  SupportSlugRobotsDottxtRoute: SupportSlugRobotsDottxtRoute,
  SupportSlugSitemapDotxmlRoute: SupportSlugSitemapDotxmlRoute,
  SupportSlugIndexRoute: SupportSlugIndexRoute,
  SupportSlugThreadsIdRoute: SupportSlugThreadsIdRoute,
  SupportSlugThreadsIndexRoute: SupportSlugThreadsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
