/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StatusIndicatorRouteImport } from './routes/status-indicator'
import { Route as CompositeRouteImport } from './routes/composite'
import { Route as CommandRouteImport } from './routes/command'
import { Route as ButtonsRouteImport } from './routes/buttons'
import { Route as AvatarRouteImport } from './routes/avatar'
import { Route as IndexRouteImport } from './routes/index'

const StatusIndicatorRoute = StatusIndicatorRouteImport.update({
  id: '/status-indicator',
  path: '/status-indicator',
  getParentRoute: () => rootRouteImport,
} as any)
const CompositeRoute = CompositeRouteImport.update({
  id: '/composite',
  path: '/composite',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandRoute = CommandRouteImport.update({
  id: '/command',
  path: '/command',
  getParentRoute: () => rootRouteImport,
} as any)
const ButtonsRoute = ButtonsRouteImport.update({
  id: '/buttons',
  path: '/buttons',
  getParentRoute: () => rootRouteImport,
} as any)
const AvatarRoute = AvatarRouteImport.update({
  id: '/avatar',
  path: '/avatar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/avatar': typeof AvatarRoute
  '/buttons': typeof ButtonsRoute
  '/command': typeof CommandRoute
  '/composite': typeof CompositeRoute
  '/status-indicator': typeof StatusIndicatorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/avatar': typeof AvatarRoute
  '/buttons': typeof ButtonsRoute
  '/command': typeof CommandRoute
  '/composite': typeof CompositeRoute
  '/status-indicator': typeof StatusIndicatorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/avatar': typeof AvatarRoute
  '/buttons': typeof ButtonsRoute
  '/command': typeof CommandRoute
  '/composite': typeof CompositeRoute
  '/status-indicator': typeof StatusIndicatorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/avatar'
    | '/buttons'
    | '/command'
    | '/composite'
    | '/status-indicator'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/avatar'
    | '/buttons'
    | '/command'
    | '/composite'
    | '/status-indicator'
  id:
    | '__root__'
    | '/'
    | '/avatar'
    | '/buttons'
    | '/command'
    | '/composite'
    | '/status-indicator'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AvatarRoute: typeof AvatarRoute
  ButtonsRoute: typeof ButtonsRoute
  CommandRoute: typeof CommandRoute
  CompositeRoute: typeof CompositeRoute
  StatusIndicatorRoute: typeof StatusIndicatorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/status-indicator': {
      id: '/status-indicator'
      path: '/status-indicator'
      fullPath: '/status-indicator'
      preLoaderRoute: typeof StatusIndicatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/composite': {
      id: '/composite'
      path: '/composite'
      fullPath: '/composite'
      preLoaderRoute: typeof CompositeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/command': {
      id: '/command'
      path: '/command'
      fullPath: '/command'
      preLoaderRoute: typeof CommandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buttons': {
      id: '/buttons'
      path: '/buttons'
      fullPath: '/buttons'
      preLoaderRoute: typeof ButtonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avatar': {
      id: '/avatar'
      path: '/avatar'
      fullPath: '/avatar'
      preLoaderRoute: typeof AvatarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AvatarRoute: AvatarRoute,
  ButtonsRoute: ButtonsRoute,
  CommandRoute: CommandRoute,
  CompositeRoute: CompositeRoute,
  StatusIndicatorRoute: StatusIndicatorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
