/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ToggleGroupRouteImport } from './routes/toggle-group'
import { Route as StatusIndicatorRouteImport } from './routes/status-indicator'
import { Route as SegmentedControlRouteImport } from './routes/segmented-control'
import { Route as CompositeRouteImport } from './routes/composite'
import { Route as CommandRouteImport } from './routes/command'
import { Route as ColorsRouteImport } from './routes/colors'
import { Route as ButtonRouteImport } from './routes/button'
import { Route as AvatarRouteImport } from './routes/avatar'
import { Route as IndexRouteImport } from './routes/index'

const ToggleGroupRoute = ToggleGroupRouteImport.update({
  id: '/toggle-group',
  path: '/toggle-group',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusIndicatorRoute = StatusIndicatorRouteImport.update({
  id: '/status-indicator',
  path: '/status-indicator',
  getParentRoute: () => rootRouteImport,
} as any)
const SegmentedControlRoute = SegmentedControlRouteImport.update({
  id: '/segmented-control',
  path: '/segmented-control',
  getParentRoute: () => rootRouteImport,
} as any)
const CompositeRoute = CompositeRouteImport.update({
  id: '/composite',
  path: '/composite',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandRoute = CommandRouteImport.update({
  id: '/command',
  path: '/command',
  getParentRoute: () => rootRouteImport,
} as any)
const ColorsRoute = ColorsRouteImport.update({
  id: '/colors',
  path: '/colors',
  getParentRoute: () => rootRouteImport,
} as any)
const ButtonRoute = ButtonRouteImport.update({
  id: '/button',
  path: '/button',
  getParentRoute: () => rootRouteImport,
} as any)
const AvatarRoute = AvatarRouteImport.update({
  id: '/avatar',
  path: '/avatar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/avatar': typeof AvatarRoute
  '/button': typeof ButtonRoute
  '/colors': typeof ColorsRoute
  '/command': typeof CommandRoute
  '/composite': typeof CompositeRoute
  '/segmented-control': typeof SegmentedControlRoute
  '/status-indicator': typeof StatusIndicatorRoute
  '/toggle-group': typeof ToggleGroupRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/avatar': typeof AvatarRoute
  '/button': typeof ButtonRoute
  '/colors': typeof ColorsRoute
  '/command': typeof CommandRoute
  '/composite': typeof CompositeRoute
  '/segmented-control': typeof SegmentedControlRoute
  '/status-indicator': typeof StatusIndicatorRoute
  '/toggle-group': typeof ToggleGroupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/avatar': typeof AvatarRoute
  '/button': typeof ButtonRoute
  '/colors': typeof ColorsRoute
  '/command': typeof CommandRoute
  '/composite': typeof CompositeRoute
  '/segmented-control': typeof SegmentedControlRoute
  '/status-indicator': typeof StatusIndicatorRoute
  '/toggle-group': typeof ToggleGroupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/avatar'
    | '/button'
    | '/colors'
    | '/command'
    | '/composite'
    | '/segmented-control'
    | '/status-indicator'
    | '/toggle-group'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/avatar'
    | '/button'
    | '/colors'
    | '/command'
    | '/composite'
    | '/segmented-control'
    | '/status-indicator'
    | '/toggle-group'
  id:
    | '__root__'
    | '/'
    | '/avatar'
    | '/button'
    | '/colors'
    | '/command'
    | '/composite'
    | '/segmented-control'
    | '/status-indicator'
    | '/toggle-group'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AvatarRoute: typeof AvatarRoute
  ButtonRoute: typeof ButtonRoute
  ColorsRoute: typeof ColorsRoute
  CommandRoute: typeof CommandRoute
  CompositeRoute: typeof CompositeRoute
  SegmentedControlRoute: typeof SegmentedControlRoute
  StatusIndicatorRoute: typeof StatusIndicatorRoute
  ToggleGroupRoute: typeof ToggleGroupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/toggle-group': {
      id: '/toggle-group'
      path: '/toggle-group'
      fullPath: '/toggle-group'
      preLoaderRoute: typeof ToggleGroupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status-indicator': {
      id: '/status-indicator'
      path: '/status-indicator'
      fullPath: '/status-indicator'
      preLoaderRoute: typeof StatusIndicatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/segmented-control': {
      id: '/segmented-control'
      path: '/segmented-control'
      fullPath: '/segmented-control'
      preLoaderRoute: typeof SegmentedControlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/composite': {
      id: '/composite'
      path: '/composite'
      fullPath: '/composite'
      preLoaderRoute: typeof CompositeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/command': {
      id: '/command'
      path: '/command'
      fullPath: '/command'
      preLoaderRoute: typeof CommandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colors': {
      id: '/colors'
      path: '/colors'
      fullPath: '/colors'
      preLoaderRoute: typeof ColorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/button': {
      id: '/button'
      path: '/button'
      fullPath: '/button'
      preLoaderRoute: typeof ButtonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avatar': {
      id: '/avatar'
      path: '/avatar'
      fullPath: '/avatar'
      preLoaderRoute: typeof AvatarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AvatarRoute: AvatarRoute,
  ButtonRoute: ButtonRoute,
  ColorsRoute: ColorsRoute,
  CommandRoute: CommandRoute,
  CompositeRoute: CompositeRoute,
  SegmentedControlRoute: SegmentedControlRoute,
  StatusIndicatorRoute: StatusIndicatorRoute,
  ToggleGroupRoute: ToggleGroupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
