# wrangler.toml
name = "front-desk-waitlist"
main = "./.output/server/index.mjs"
compatibility_date = "2025-04-01"
compatibility_flags = ["nodejs_compat"]
keep_vars = true

[assets]
binding = "ASSETS"
directory = "./.output/public"

[observability.logs]
enabled = true

[vars]
DB_NAME = "postgres"
DB_HOST = "aws-1-us-east-2.pooler.supabase.com"
DB_PORT = 6543

VITE_PUBLIC_POSTHOG_KEY = "phc_jXzgyEMPbtSGhFQwuwXr0ignCjz3kspvC4jjduqwxXP"
VITE_PUBLIC_POSTHOG_HOST = "https://us.i.posthog.com"
